### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by nagawa-hub** [nagawa-hub/furima-31652#26]
・フリマアプリのURL
https://furima-31652.herokuapp.com/

・Basic認証のID：furima
パスワード ：31652

・出品者用のメールアドレス：sell@sample
パスワード ：sample1

・購入者用のメールアドレス：buy@sample
パスワード ：sample1

・購入用カードの番号：4242424242424242
期限：現在より未来
セキュリティコード：123

**Comment by eeee-0000** [comment]
nagawa-hubさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
